FROM python:3.12.0b1-slim
WORKDIR /app2
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install requests
COPY . .

CMD ["python3", "-m", "flask", "--app", "client", "run", "--host=0.0.0.0"]
